title: Rock Mice
description: "Program"
owner_name: Ahaan Vaidyanathan
github_username: Ahaanv19
github_repo: "Rock_Mice" 
baseurl: "/Rock_Mice"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - /search
  - /about
  - /blogs
  - /Readme4yml